baseurl = "/"
languageCode = "en-us"
title = "Databases using R"
theme = "rstudio-docs-theme"
metadataformat = "yaml"
pluralizeListTitles =   "false"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-20375833-20"

[params]

	author = "RStudio"
	description = ""
	copyright = ""
	
	provider = ""
	repo_url = ""

  version = "1.0.0"
  logo = "/rstudio-logo.png"
  favicon = "favicon.png"
  


	[params.palette]
    	primary = "rstudio-dark"
    	accent  = "orange"

    [params.font]
    	text = "sans-serif"
    	code = "Ubuntu Mono"


[[menu.main]]
  weight = 10
	name   = "Packages"
	
[[menu.main]]
  weight = 11
	name   = "dplyr"
	parent = "Packages"
	url    = "/dplyr/"

[[menu.main]]
  weight = 12
	name   = "DBI"
	parent = "Packages"
	url    = "/dbi/"
	
[[menu.main]]
  weight = 13
	name   = "odbc"
	parent = "Packages"
	url    = "/odbc/"


[[menu.main]]
  weight = 14
	name   = "pool"
	parent = "Packages"
	url    = "/pool/"

[[menu.main]]
  weight = 15
	name   = "RStudio"
	url    = "/rstudio/connections/"
	
[[menu.main]]
  weight = 13
	name   = "Connections Pane"
	parent = "RStudio"
	url    = "/rstudio/connections/"	

[[menu.main]]
  weight = 20
	name   = "Best Practices"
	url    = "/best-practices/"
	
[[menu.main]]
  weight = 21
  name = "Setting up ODBC Drivers"
  url    = "/best-practices/drivers/"
  parent = "Best Practices"

[[menu.main]]
	weight = 22
  name   = "Run Queries Safely"
	url    = "/best-practices/run-queries-safely/"
	parent = "Best Practices"

[[menu.main]]
  weight = 23
	name   = "Securing Deployed Content"
	url    = "/best-practices/deployment/"
	parent = "Best Practices"	
	
[[menu.main]]
  weight = 24
	name   = "Securing Credentials"
	url    = "/best-practices/managing-credentials/"
	parent = "Best Practices"	

[[menu.main]]
  weight = 25
	name   = "Making Scripts Portable"
	url    = "/best-practices/portable-code/"
	parent = "Best Practices"	  

[[menu.main]]
  weight = 26
	name   = "Creating Visualizations"
	url    = "/best-practices/visualization/"
	parent = "Best Practices"	  

[[menu.main]]
  weight = 30
	name   = "Databases"
	url    = "/databases/"
	
[[menu.main]]
  weight = 31
	name   = "MS SQL Server"
	url    = "/databases/microsoft-sql-server/"
	parent = "Databases"	
[[menu.main]]
  weight = 32
	name   = "Oracle"
	url    = "/databases/oracle/"
	parent = "Databases"	
[[menu.main]]
  weight = 33
	name   = "Hive"
	url    = "/databases/hive/"
	parent = "Databases"	
[[menu.main]]
  weight = 34
	name   = "Impala"
	url    = "/databases/impala/"
	parent = "Databases"	
[[menu.main]]
  weight = 35
	name   = "PostgreSQL"
	url    = "/databases/postgresql/"
	parent = "Databases"	
[[menu.main]]
  weight = 36
	name   = "Redshift"
	url    = "/databases/redshift/"
	parent = "Databases"
[[menu.main]]
  weight = 37
	name   = "Salesforce"
	url    = "/databases/salesforce/"
	parent = "Databases"
[[menu.main]]
  weight = 38
	name   = "MySQL"
	url    = "/databases/my-sql/"
	parent = "Databases"
[[menu.main]]
  weight = 39
	name   = "SQLite"
	url    = "/databases/sqlite/"
	parent = "Databases"
	[[menu.main]]
  weight = 40
	name   = "Big Query"
	url    = "/databases/big-query/"
	parent = "Databases"
[[menu.main]]
  weight = 41
	name   = "Other Databases"
	url    = "/databases/other-databases/"
	parent = "Databases"
[[menu.main]]
  weight = 50
	name   = "Advanced"
	url    = "/advanced/"

[[menu.main]]
  weight = 51
	name   = "DBI Backend"
	parent = "Advanced"
	url    = "/advanced/backend/"
	
[[menu.main]]
  weight = 52
	name   = "SQL Translation"
	parent = "Advanced"
	url    = "/advanced/translation/"

[[menu.main]]
  weight = 52
	name   = "Connection Contract"
	parent = "Advanced"
	url    = "/advanced/contract/"

[[menu.main]]
  weight = 52
	name   = "Connection Snippet"
	parent = "Advanced"
	url    = "/advanced/snippets/"

	
[[menu.main]]
  weight = 60
	name   = "Other Resources"
	url    = "/other_resources/media/"
	
[[menu.main]]
  weight = 61
	name   = "Media"
	parent   = "Other Resources"
	url    = "/other_resources/media/"



	
[social]
	twitter = "rstudio"
	github  = "rstudio"
	email   = "info@rstudio.com"


