baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "Using Databases in R"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true

[params]

	author = "RStudio"
	description = "test"
	copyright = ""
	
	provider = ""
	repo_url = ""

  version = "1.0.0"
  logo = "/rstudio-logo.png"
  favicon = "favicon.png"

	[params.palette]
    	primary = "rstudio-dark"
    	accent  = "orange"

    [params.font]
    	text = "sans-serif"
    	code = "Ubuntu Mono"


[[menu.main]]
  weight = 5
	name   = "Packages"
	url    = "/"

[[menu.main]]
  weight = 10
	name   = "dplyr"
	parent = "Packages"
	url    = "dplyr/"


[[menu.main]]
  weight = 11
	name   = "DBI"
	parent = "Packages"
	url    = "dbi/"

[[menu.main]]
  weight = 30
	name   = "Best Practices"
	url    = "/"
	
[[menu.main]]
  weight = 31
  name = "Finding ODBC Drivers"
  url = "drivers/"
  parent = "Best Practices"

[[menu.main]]
	weight = 31
  name   = "Run Queries Safely"
	url    = "run-queries-safely/"
	parent = "Best Practices"

[[menu.main]]
  weight = 34
	name   = "Deploying Content"
	url    = "deployment/"
	parent = "Best Practices"	
	
[[menu.main]]
  weight = 34
	name   = "Securing Credentials"
	url    = "managing-credentials/"
	parent = "Best Practices"	
  

[[menu.main]]
  weight = 54
	name   = "Advanced"
	url    = "/"

[[menu.main]]
	name   = "DBI Backend"
	parent = "Advanced"
	url    = "/backend"
	
[[menu.main]]
  weight = 56
	name   = "SQL Translation"
	parent = "Advanced"
	url    = "/translation"
	
[social]
	twitter = "rstudio"
	github  = "rstudio"
	email   = "info@rstudio.com"


