baseurl = "/"
languageCode = "en-us"
title = "Using Databases in R"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true

[params]

	author = "RStudio"
	description = "test"
	copyright = ""
	
	provider = ""
	repo_url = ""

  version = "1.0.0"
  logo = "/rstudio-logo.png"
  favicon = "favicon.png"

	[params.palette]
    	primary = "rstudio-theme"
    	accent  = "orange"

    [params.font]
    	text = "sans-serif"
    	code = "Ubuntu Mono"


[[menu.main]]
  weight = 10
	name   = "DBI package"
	url    = "dbi/"

[[menu.main]]
  weight = 11
	name   = "dplyr package"
	url    = "dplyr/"

[[menu.main]]
  weight = 30
	name   = "Best Practices"
	url    = "/"

[[menu.main]]
	weight = 31
  name   = "Run Queries Safely"
	url    = "run-queries-safely/"
	parent = "Best Practices"


[[menu.main]]
  weight = 34
	name   = "Deploying Content"
	url    = "deployment/"
	parent = "Best Practices"	
  
  
[[menu.main]]
	name   = "Examples"
	url    = "examples/"

[social]
	twitter = "rstudio"
	github  = "rstudio"
	email   = "info@rstudio.com"




